"""empty message

Revision ID: 162113d6db86
Revises: 30aada49b084
Create Date: 2017-02-22 05:59:34.293146

"""

# revision identifiers, used by Alembic.
revision = '162113d6db86'
down_revision = '30aada49b084'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_article', sa.Column('crdate', sa.DateTime(timezone=True), server_default='now()', nullable=False))
    op.add_column('users', sa.Column('crdate', sa.DateTime(timezone=True), server_default='now()', nullable=False))
    op.add_column('users', sa.Column('validated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('validation_code', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('fio', sa.VARCHAR(length=255), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fio')
    op.drop_column('users', 'validation_code')
    op.drop_column('users', 'validated')
    op.drop_column('users', 'crdate')
    op.drop_column('content_article', 'crdate')
    ### end Alembic commands ###
