"""empty message

Revision ID: 2842df07220b
Revises: 2d7beb12606d
Create Date: 2017-03-07 01:35:02.861349

"""

# revision identifiers, used by Alembic.
revision = '2842df07220b'
down_revision = '2d7beb12606d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seminars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crdate', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('datebegin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), server_default='', nullable=False),
    #sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('seminar_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seminar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seminar_id'], ['seminars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seminar_users')
    op.drop_table('seminars')
    ### end Alembic commands ###
