"""empty message

Revision ID: 2d7beb12606d
Revises: 162113d6db86
Create Date: 2017-02-22 11:16:19.650473

"""

# revision identifiers, used by Alembic.
revision = '2d7beb12606d'
down_revision = '162113d6db86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=32), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    ### end Alembic commands ###
