"""empty message

Revision ID: 2d8012c2b8df
Revises: 2842df07220b
Create Date: 2017-03-07 20:44:09.967816

"""

# revision identifiers, used by Alembic.
revision = '2d8012c2b8df'
down_revision = '2842df07220b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seminars', sa.Column('body', sa.TEXT(), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seminars', 'body')
    ### end Alembic commands ###
