"""empty message

Revision ID: 68c8c0c0c3c
Revises: 2d8012c2b8df
Create Date: 2017-03-08 17:40:15.344506

"""

# revision identifiers, used by Alembic.
revision = '68c8c0c0c3c'
down_revision = '2d8012c2b8df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crdate', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('datebegin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), server_default='', nullable=False),
    sa.Column('body', sa.TEXT(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    ### end Alembic commands ###
